# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QProgressBar,
    QPushButton, QSizePolicy, QStatusBar, QTextEdit,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(491, 513)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.trainPushButton = QPushButton(self.centralwidget)
        self.trainPushButton.setObjectName(u"trainPushButton")
        self.trainPushButton.setGeometry(QRect(200, 10, 75, 24))
        self.trainingInfoGroupBox = QGroupBox(self.centralwidget)
        self.trainingInfoGroupBox.setObjectName(u"trainingInfoGroupBox")
        self.trainingInfoGroupBox.setGeometry(QRect(10, 200, 201, 251))
        self.currentEpochProgressBar = QProgressBar(self.trainingInfoGroupBox)
        self.currentEpochProgressBar.setObjectName(u"currentEpochProgressBar")
        self.currentEpochProgressBar.setGeometry(QRect(100, 40, 101, 23))
        self.currentEpochProgressBar.setValue(0)
        self.label = QLabel(self.trainingInfoGroupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 40, 81, 16))
        self.label_2 = QLabel(self.trainingInfoGroupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 20, 49, 16))
        self.epochNumberProgressLabel = QLabel(self.trainingInfoGroupBox)
        self.epochNumberProgressLabel.setObjectName(u"epochNumberProgressLabel")
        self.epochNumberProgressLabel.setGeometry(QRect(110, 20, 49, 16))
        self.metricsTextEdit = QTextEdit(self.trainingInfoGroupBox)
        self.metricsTextEdit.setObjectName(u"metricsTextEdit")
        self.metricsTextEdit.setGeometry(QRect(10, 90, 181, 151))
        self.label_3 = QLabel(self.trainingInfoGroupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 70, 49, 16))
        self.trainingSettingsGroupBox = QGroupBox(self.centralwidget)
        self.trainingSettingsGroupBox.setObjectName(u"trainingSettingsGroupBox")
        self.trainingSettingsGroupBox.setGeometry(QRect(10, 50, 201, 151))
        self.epochsNumberLineEdit = QLineEdit(self.trainingSettingsGroupBox)
        self.epochsNumberLineEdit.setObjectName(u"epochsNumberLineEdit")
        self.epochsNumberLineEdit.setGeometry(QRect(130, 30, 61, 21))
        self.label_4 = QLabel(self.trainingSettingsGroupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 30, 49, 16))
        self.batchSizeLineEdit = QLineEdit(self.trainingSettingsGroupBox)
        self.batchSizeLineEdit.setObjectName(u"batchSizeLineEdit")
        self.batchSizeLineEdit.setGeometry(QRect(130, 60, 61, 21))
        self.label_5 = QLabel(self.trainingSettingsGroupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 60, 61, 16))
        self.label_6 = QLabel(self.trainingSettingsGroupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(8, 90, 61, 16))
        self.imageSizeLineEdit = QLineEdit(self.trainingSettingsGroupBox)
        self.imageSizeLineEdit.setObjectName(u"imageSizeLineEdit")
        self.imageSizeLineEdit.setGeometry(QRect(130, 90, 61, 21))
        self.label_7 = QLabel(self.trainingSettingsGroupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(8, 120, 61, 16))
        self.deviceLineEdit = QLineEdit(self.trainingSettingsGroupBox)
        self.deviceLineEdit.setObjectName(u"deviceLineEdit")
        self.deviceLineEdit.setEnabled(False)
        self.deviceLineEdit.setGeometry(QRect(130, 120, 61, 21))
        self.abortPushButton = QPushButton(self.centralwidget)
        self.abortPushButton.setObjectName(u"abortPushButton")
        self.abortPushButton.setGeometry(QRect(290, 10, 75, 24))
        self.useWeightsCheckBox = QCheckBox(self.centralwidget)
        self.useWeightsCheckBox.setObjectName(u"useWeightsCheckBox")
        self.useWeightsCheckBox.setGeometry(QRect(10, 10, 91, 20))
        self.loadWeightsPushButton = QPushButton(self.centralwidget)
        self.loadWeightsPushButton.setObjectName(u"loadWeightsPushButton")
        self.loadWeightsPushButton.setGeometry(QRect(100, 10, 81, 24))
        self.analysePushButton = QPushButton(self.centralwidget)
        self.analysePushButton.setObjectName(u"analysePushButton")
        self.analysePushButton.setGeometry(QRect(330, 60, 75, 24))
        self.logTextEdit = QTextEdit(self.centralwidget)
        self.logTextEdit.setObjectName(u"logTextEdit")
        self.logTextEdit.setGeometry(QRect(220, 200, 261, 271))
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(230, 180, 49, 16))
        self.selectFileForAnalysisPushButton = QPushButton(self.centralwidget)
        self.selectFileForAnalysisPushButton.setObjectName(u"selectFileForAnalysisPushButton")
        self.selectFileForAnalysisPushButton.setGeometry(QRect(230, 60, 75, 24))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(220, 100, 61, 16))
        self.confidenceThresholdLineEdit = QLineEdit(self.centralwidget)
        self.confidenceThresholdLineEdit.setObjectName(u"confidenceThresholdLineEdit")
        self.confidenceThresholdLineEdit.setGeometry(QRect(340, 100, 61, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 491, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        self.trainPushButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Select dataset (.yaml file) with File menu, setup training settings and click this button to train YOLO11 model. Default path for dataset - '<span style=\" font-family:'Courier New'; color:#6a8759;\">./dataset/data.yaml</span>'.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.trainPushButton.setText(QCoreApplication.translate("MainWindow", u"Train", None))
        self.trainingInfoGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Training info", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Current epoch", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Epoch", None))
        self.epochNumberProgressLabel.setText(QCoreApplication.translate("MainWindow", u"0/0", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Metrics", None))
        self.trainingSettingsGroupBox.setTitle(QCoreApplication.translate("MainWindow", u"Training settings", None))
        self.epochsNumberLineEdit.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Epochs", None))
        self.batchSizeLineEdit.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Batch size", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Image size", None))
        self.imageSizeLineEdit.setText(QCoreApplication.translate("MainWindow", u"320", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Device", None))
        self.deviceLineEdit.setText(QCoreApplication.translate("MainWindow", u"cpu", None))
#if QT_CONFIG(tooltip)
        self.abortPushButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Abort training</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.abortPushButton.setText(QCoreApplication.translate("MainWindow", u"Abort", None))
#if QT_CONFIG(tooltip)
        self.useWeightsCheckBox.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Set checked if want to train with weights selected with 'load button'.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.useWeightsCheckBox.setText(QCoreApplication.translate("MainWindow", u"use weights?", None))
#if QT_CONFIG(tooltip)
        self.loadWeightsPushButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Select weights file for model. Weights are used for training if 'use weight?' is checked.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.loadWeightsPushButton.setText(QCoreApplication.translate("MainWindow", u"Load weights", None))
#if QT_CONFIG(tooltip)
        self.analysePushButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Analyse selected file. If 'use weights?' is checked use model with loaded weight. Otherwise use default model. </p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.analysePushButton.setText(QCoreApplication.translate("MainWindow", u"Analyse", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Log", None))
#if QT_CONFIG(tooltip)
        self.selectFileForAnalysisPushButton.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Select file to analyse with YOLO model.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.selectFileForAnalysisPushButton.setText(QCoreApplication.translate("MainWindow", u"Select file", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Confidence", None))
#if QT_CONFIG(tooltip)
        self.confidenceThresholdLineEdit.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Confidence threshold. Value between 0-1. If prediction made with confidence below set threshold it will not be displayed.</p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.confidenceThresholdLineEdit.setText(QCoreApplication.translate("MainWindow", u"0.2", None))
    # retranslateUi

